In [ ]:
# installs the openpyxl library, which is used to work with Excel files (.xlsx format) in Python.
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)

In [ ]:
from google.colab import drive
# Pandas is used for data manipulation and analysis.
import pandas as pd


# Mount Google Drive
drive.mount('/content/drive')

# Specify the path to your Excel file in Google Drive
file_path = '/content/drive/MyDrive/GMR/GKEL_Coal_yard_MIS.XLSX'  # Correct file path here

# Load the data from the specific sheet into a pandas DataFrame
df1 = pd.read_excel(file_path, sheet_name="PILE-1A")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
df1
df1_cleaned = df1.iloc[3:10,:19]
#df1_cleaned
# Reset the index of the sliced DataFrame
# df1_reset = df1_cleaned.reset_index(drop=True)

# Display the reset DataFrame
# df1_reset

# df1_reset.to_excel('/content/drive/MyDrive/GMR/ump.xlsx')
#df1 = pd.read_excel("/content/drive/MyDrive/GMR/GKEL_Coal_yard_MIS.XLSX", header=0)  # Use the first row as column names
#df1

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df1_cleaned.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18'],
      dtype='object')

In [ ]:
df1_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)

In [ ]:
df1_cleaned.columns

Index(['STACKING DATE', 'RAKE NO', 'SPUR', 'SUB PILE', 'TOP/BOTTOM', 'ST QNTY',
       'GCV', 'NaN', 'RECLIAM DATE', 'RC-QNTY', 'AVAILABLE QUANTITY', 'AGING',
       'TOP GCV', 'TOP QNTY', 'BTM GCV', 'BTM QNTY', 'coal above 3500',
       '3100-3500', '<3100'],
      dtype='object')

In [ ]:
df1_cleaned
df1_cleaned = df1_cleaned.drop(3, axis=0)

## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df1_cleaned["Pile_id"]="1A"
df1_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-14 00:00:00,27,2,1,B,3385,3304,As per result,NaN,NaN,3385,84,0,0,3304,3385,0,3385,0,1A
5,2024-10-15 00:00:00,29,2,1,B,3092,3244,As per result,NaN,NaN,3092,83,0,0,3244,3092,0,3092,0,1A
6,2024-10-25 00:00:00,58,SILO,2,B,4668,2971,As per result,NaN,NaN,4668,73,0,0,2971,4668,0,0,4668,1A
7,2024-10-26 00:00:00,65,SILO,2,T,3555,3585,As per result,NaN,NaN,3555,72,3585,3555,0,0,3555,0,0,1A
8,2024-10-26 00:00:00,68,SILO,2,T,3246,3753,As per result,NaN,NaN,3246,72,3753,3246,0,0,3246,0,0,1A
9,2024-11-12 00:00:00,19,2,1,T,3339,2890,As per result,NaN,NaN,3339,55,2890,3339,0,0,0,0,3339,1A

In [ ]:
#df1_cleaned.to_csv("/content/drive/MyDrive/GMR/ds1_cleaned.csv")

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df2 = pd.read_excel(file_path, sheet_name="PILE-1B")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df2_cleaned = df2.iloc[3:10,:19]
#df2_cleaned

In [ ]:
df2_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df2_cleaned = df2_cleaned.drop(3, axis=0)

## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df2_cleaned["Pile_id"]="1B"

df2_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-09-12 00:00:00,29,10,1,B,3910,2357,As per result,NaN,NaN,3910,116,0,0,2357,3910,0,0,3910,1B
5,2024-10-02 00:00:00,2,1,2,B,3750,3206,As per result,NaN,NaN,3750,96,0,0,3206,3750,0,3750,0,1B
6,2024-10-10 00:00:00,21,1,2,T,3264,3034,As per result,NaN,NaN,3264,88,3034,3264,0,0,0,0,3264,1B
7,2024-10-15 00:00:00,31,1,2,T,3568,3034,As per result,NaN,NaN,3568,83,3034,3568,0,0,0,0,3568,1B
8,2024-11-02 00:00:00,85,5,2,T,2595,2960,As per result,NaN,NaN,2595,65,2960,2595,0,0,0,0,2595,1B
9,2024-11-03 00:00:00,88,5,2,T,3143,3396,As per result,NaN,NaN,3143,64,3396,3143,0,0,0,3143,0,1B

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df3 = pd.read_excel(file_path, sheet_name="PILE-1C")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df3_cleaned = df3.iloc[3:10,:19]
#df3_cleaned

In [ ]:
df3_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df3_cleaned = df3_cleaned.drop(3, axis=0)
df3_cleaned["Pile_id"]="1C"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df3_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-18 00:00:00,35,SILO,1,B,2800,3523,As per result,NaN,NaN,2800,80,0,0,3523,2800,2800,0,0,1C
5,2024-10-23 00:00:00,52,SILO,1,B,3716,3574.033626,As per result,NaN,NaN,3716,75,0,0,3574.033626,3716,3716,0,0,1C
6,2024-10-24 00:00:00,57,SILO,1,T,4308,3653,As per result,NaN,NaN,4308,74,3653,4308,0,0,4308,0,0,1C
7,2024-10-25 00:00:00,62,SILO,1,T,2500,3274.997947,As per result,NaN,NaN,2500,73,3274.997947,2500,0,0,0,2500,0,1C
8,2024-10-25 00:00:00,63,SILO,1,T,2700,3585.334803,As per result,NaN,NaN,2700,73,3585.334803,2700,0,0,2700,0,0,1C
9,2024-11-02 00:00:00,86,SILO,1,T,1172,3237,As per result,NaN,NaN,1172,65,3237,1172,0,0,0,1172,0,1C

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df4 = pd.read_excel(file_path, sheet_name="PILE-1D")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df4_cleaned = df4.iloc[3:10,:19]
#df4_cleaned

In [ ]:
df4_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df4_cleaned = df4_cleaned.drop(3, axis=0)
df4_cleaned["Pile_id"]="1D"

## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df4_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-21 00:00:00,45,5,1,B,3970,3355.556506,As per result,NaN,NaN,3970,77,0,0,3355.556506,3970,0,3970,0,1D
5,2024-10-22 00:00:00,46,5,1,B,2930,3618.133722,As per result,NaN,NaN,2930,76,0,0,3618.133722,2930,2930,0,0,1D
6,2024-10-22 00:00:00,48,5,1,T,3475,3597,As per result,NaN,NaN,3475,76,3597,3475,0,0,3475,0,0,1D
7,2024-10-23 00:00:00,51,5,1,T,3580,3129.645473,As per result,NaN,NaN,3580,75,3129.645473,3580,0,0,0,3580,0,1D
8,2024-10-24 00:00:00,55,5,1,T,3700,3527.867287,As per result,NaN,NaN,3700,74,3527.867287,3700,0,0,3700,0,0,1D
9,2024-11-06 00:00:00,6,5,1,T,3614,3859.0587,As per result,NaN,NaN,3614,61,3859.0587,3614,0,0,3614,0,0,1D

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df5 = pd.read_excel(file_path, sheet_name="PILE-2A")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df5_cleaned = df5.iloc[3:10,:19]
#df5_cleaned

In [ ]:
df5_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df5_cleaned = df5_cleaned.drop(3, axis=0)
df5_cleaned["Pile_id"]="2A"

## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df5_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-11-25 00:00:00,50,1,1,B,3784,2435,As per result,NaN,NaN,3784,42,0,0,2435,3784,0,0,3784,2A
5,2024-11-28 00:00:00,62,1,1,B,4166,2854,Approx,NaN,NaN,4166,39,0,0,2854,4166,0,0,4166,2A
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2A
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2A
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2A
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2A

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df6 = pd.read_excel(file_path, sheet_name="PILE-2B")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df6_cleaned = df6.iloc[3:10,:19]
#df6_cleaned

In [ ]:
df6_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df6cleaned = df6_cleaned.drop(3, axis=0)
df6_cleaned["Pile_id"]="2B"

## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df6_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
3,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3200,2900-3200,<2900,2B
4,2024-11-27 00:00:00,58,6,1,B,4538,3487,As per result,NaN,NaN,4538,40,0,0,3487,4538,0,4538,0,2B
5,2024-11-28 00:00:00,64,SILO,2,B,3867,3119,Approx,NaN,NaN,3867,39,0,0,3119,3867,0,3867,0,2B
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2B
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2B
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2B
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2B

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df7 = pd.read_excel(file_path, sheet_name="PILE-2C")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df7_cleaned = df7.iloc[3:10,:19]
#df7_cleaned

In [ ]:
df7_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df7_cleaned = df7_cleaned.drop(3, axis=0)
df7_cleaned["Pile_id"]="2C"

## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df7_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-09 00:00:00,17,4,1,B,3250,2891,As per result,NaN,NaN,3250,89,0,0,2891,3250,0,0,3250,2C
5,2024-10-26 00:00:00,64,4,1,B,1900,2731.067663,As per result,NaN,NaN,1900,72,0,0,2731.067663,1900,0,0,1900,2C
6,2024-10-26 00:00:00,66,2,2,B,1700,2866.359424,As per result,NaN,NaN,1700,72,0,0,2866.359424,1700,0,0,1700,2C
7,2024-10-29 00:00:00,73,2,2,B,3600,2903,As per result,NaN,NaN,3600,69,0,0,2903,3600,0,0,3600,2C
8,2024-10-30 00:00:00,78,1,2,B,6019,3592,As per result,NaN,NaN,6019,68,0,0,3592,6019,6019,0,0,2C
9,2024-10-31 00:00:00,81,2,2,T,3200,3398,As per result,NaN,NaN,3200,67,3398,3200,0,0,0,3200,0,2C

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df8 = pd.read_excel(file_path, sheet_name="PILE-2D")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df8_cleaned = df8.iloc[3:10,:19]
#df8_cleaned

In [ ]:
df8_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df8_cleaned = df8_cleaned.drop(3, axis=0)
df8_cleaned["Pile_id"]="2D"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df8_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-11-28 00:00:00,63,5,1,B,3926,3637,Approx,NaN,NaN,3926,39,0,0,3637,3926,3926,0,0,2D
5,2024-11-29 00:00:00,65,5,1,B,3580,3637,Approx,NaN,NaN,3580,38,0,0,3637,3580,3580,0,0,2D
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2D
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2D
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2D
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,2D

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df9 = pd.read_excel(file_path, sheet_name="PILE-3A")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df9_cleaned = df9.iloc[3:10,:19]
#df9_cleaned

In [ ]:
df9_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df9_cleaned = df9_cleaned.drop(3, axis=0)
df9_cleaned["Pile_id"]="3A"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df9_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-09-20 00:00:00,57,2,1,B,3344,3128,As per result,NaN,NaN,3344,108,0,0,3128,3344,0,3344,0,3A
5,2024-09-30 00:00:00,80,3,2,B,3133,2874,As per result,NaN,NaN,3133,98,0,0,2874,3133,0,0,3133,3A
6,2024-11-02 00:00:00,86,SILO,2,B,3800,3237,As per result,NaN,NaN,3800,65,0,0,3237,3800,0,3800,0,3A
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,3A
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,3A
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,3A

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df10 = pd.read_excel(file_path, sheet_name="PILE-3B")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df10_cleaned = df10.iloc[3:10,:19]
#df10_cleaned

In [ ]:
df10_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df10_cleaned = df10_cleaned.drop(3, axis=0)
df10_cleaned["Pile_id"]="3B"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df10_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-09-17 00:00:00,45,5,2,B,3836,3127.265308,As per result,NaN,NaN,3836,111,0,0,3127.265308,3836,0,3836,0,3B
5,2024-09-18 00:00:00,47,5,2,B,3540,2908.960922,As per result,NaN,NaN,3540,110,0,0,2908.960922,3540,0,0,3540,3B
6,2024-09-18 00:00:00,48,5,2,T,3032,3173,As per result,NaN,NaN,3032,110,3173,3032,0,0,0,3032,0,3B
7,2024-09-19 00:00:00,51,5,1,B,2750,3346.175155,As per result,2024-11-28 00:00:00,2750,0,109,0,0,3346.175155,0,0,0,0,3B
8,2024-09-19 00:00:00,52,5,1,B,3500,3248.312,As per result,2024-11-28 00:00:00,3500,0,109,0,0,3248.312,0,0,0,0,3B
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,3B

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df11 = pd.read_excel(file_path, sheet_name="PILE-3C")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df11_cleaned = df11.iloc[3:10,:19]
#df11_cleaned

In [ ]:
df11_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df11_cleaned = df11_cleaned.drop(3, axis=0)
df11_cleaned["Pile_id"]="3C"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df11_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-11-23 00:00:00,45,SILO,1,B,2690,3208.511734,As per result,NaN,NaN,2690,44,0,0,3208.511734,2690,0,2690,0,3C
5,2024-11-24 00:00:00,47,8,2,B,3650,2900.878048,As per result,NaN,NaN,3650,43,0,0,2900.878048,3650,0,0,3650,3C
6,2024-11-24 00:00:00,49,SILO,1,B,2326,3223.426043,As per result,NaN,NaN,2326,43,0,0,3223.426043,2326,0,2326,0,3C
7,2024-11-25 00:00:00,53,SILO,1,T,3348,3153,Approx,NaN,NaN,3348,42,3153,3348,0,0,0,3348,0,3C
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,3C
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,3C

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df12 = pd.read_excel(file_path, sheet_name="PILE-3D")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df12_cleaned = df12.iloc[3:10,:19]
#df12_cleaned

In [ ]:
df12_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df12_cleaned = df12_cleaned.drop(3, axis=0)
df12_cleaned["Pile_id"]="3D"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df12_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-11-19 00:00:00,34,6,1,B,3752,3355.353383,As per result,NaN,NaN,3752,48,0,0,3355.353383,3752,0,3752,0,3D
5,2024-11-19 00:00:00,37,4,2,B,3900,2641.159521,As per result,NaN,NaN,3900,48,0,0,2641.159521,3900,0,0,3900,3D
6,2024-11-20 00:00:00,38,6,1,B,3800,3631.116066,As per result,NaN,NaN,3800,47,0,0,3631.116066,3800,3800,0,0,3D
7,2024-11-21 00:00:00,41,6,1,T,2729,3623.369997,As per result,NaN,NaN,2729,46,3623.369997,2729,0,0,2729,0,0,3D
8,2024-11-24 00:00:00,48,6,1,T,4086,2991.231711,As per result,NaN,NaN,4086,43,2991.231711,4086,0,0,0,0,4086,3D
9,2024-11-25 00:00:00,51,6,1,T,3358,3417,As per result,NaN,NaN,3358,42,3417,3358,0,0,0,3358,0,3D

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df13 = pd.read_excel(file_path, sheet_name="PILE-4A")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df13_cleaned = df13.iloc[3:10,:19]
#df13_cleaned

In [ ]:
df13_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df13_cleaned = df13_cleaned.drop(3, axis=0)
df13_cleaned["Pile_id"]="4A"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df13_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-09 00:00:00,20,3,1,B,5075,2818,As per result,2024-10-23 00:00:00,1800,3275,89,0,0,2818,3275,0,0,3275,4A
5,2024-10-30 00:00:00,78,1,1,B,2453,3592,As per result,NaN,NaN,2453,68,0,0,3592,2453,2453,0,0,4A
6,2024-11-01 00:00:00,79,5,2,B,3485,3375,As per result,NaN,NaN,3485,66,0,0,3375,3485,0,3485,0,4A
7,2024-11-03 00:00:00,89,SILO,1,T,4862,3246,As per result,NaN,NaN,4862,64,3246,4862,0,0,0,4862,0,4A
8,2024-11-25 00:00:00,54,4,2,T,3126,2766,As per result,NaN,NaN,3126,42,2766,3126,0,0,0,0,3126,4A
9,2024-11-27 00:00:00,61,SILO,1,T,4273,3119,Approx,NaN,NaN,4273,40,3119,4273,0,0,0,4273,0,4A

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df14 = pd.read_excel(file_path, sheet_name="PILE-4B")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df14_cleaned = df14.iloc[3:10,:19]
#df14_cleaned

In [ ]:
df14_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df14_cleaned = df14_cleaned.drop(3, axis=0)
df14_cleaned["Pile_id"]="4B"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df14_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-10 00:00:00,23,6,1,B,4341,3431,As per result,NaN,NaN,4341,88,0,0,3431,4341,0,4341,0,4B
5,2024-10-19 00:00:00,38,6,1,B,4002,3203,As per result,NaN,NaN,4002,79,0,0,3203,4002,0,4002,0,4B
6,2024-10-20 00:00:00,42,6,1,T,2473,3835,As per result,NaN,NaN,2473,78,3835,2473,0,0,2473,0,0,4B
7,2024-10-22 00:00:00,50,6,1,T,3344,3677,As per result,NaN,NaN,3344,76,3677,3344,0,0,3344,0,0,4B
8,2024-10-26 00:00:00,67,6,1,T,3480,3212.001037,As per result,NaN,NaN,3480,72,3212.001037,3480,0,0,0,3480,0,4B
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,4B

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df15 = pd.read_excel(file_path, sheet_name="PILE-4C")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df15_cleaned = df15.iloc[3:10,:19]
#df15_cleaned

In [ ]:
df15_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df15_cleaned = df15_cleaned.drop(3, axis=0)
df15_cleaned["Pile_id"]="4C"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df15_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-20 00:00:00,40,1,1,B,3025,3214.648958,As per result,NaN,NaN,3025,78,0,0,3214.648958,3025,0,3025,0,4C
5,2024-10-20 00:00:00,41,1,1,B,3051,3686.885403,As per result,NaN,NaN,3051,78,0,0,3686.885403,3051,3051,0,0,4C
6,2024-10-20 00:00:00,43,2,2,B,3085,3427,As per result,NaN,NaN,3085,78,0,0,3427,3085,0,3085,0,4C
7,2024-10-21 00:00:00,44,2,2,B,6036,3751.791336,As per result,NaN,NaN,6036,77,0,0,3751.791336,6036,6036,0,0,4C
8,2024-10-22 00:00:00,49,1,1,T,858,3141,As per result,NaN,NaN,858,76,3141,858,0,0,0,858,0,4C
9,2024-10-23 00:00:00,53,2,2,T,1020,3306,As per result,NaN,NaN,1020,75,3306,1020,0,0,0,1020,0,4C

In [ ]:
# Load the data from the specific sheet into a pandas DataFrame
df16 = pd.read_excel(file_path, sheet_name="PILE-4D")  # Use sheet_name as a parameter

# Display the first few rows of the DataFrame
#df2
df16_cleaned = df16.iloc[3:10,:19]
#df16_cleaned

In [ ]:
df16_cleaned.rename(columns={'Unnamed: 0': 'STACKING DATE','Unnamed: 1':'RAKE NO','Unnamed: 2': 'SPUR','Unnamed: 3':'SUB PILE','Unnamed: 4':'TOP/BOTTOM','Unnamed: 5':'ST QNTY','Unnamed: 6':'GCV','Unnamed: 7':'NaN','Unnamed: 8':'RECLIAM DATE','Unnamed: 9':'RC-QNTY','Unnamed: 10':'AVAILABLE QUANTITY','Unnamed: 11':'AGING','Unnamed: 12':'TOP GCV','Unnamed: 13':'TOP QNTY','Unnamed: 14':'BTM GCV','Unnamed: 15':'BTM QNTY','Unnamed: 16':'coal above 3500','Unnamed: 17':'3100-3500', 'Unnamed: 18':'<3100'}, inplace=True)


df16_cleaned = df16_cleaned.drop(3, axis=0)
df16_cleaned["Pile_id"]="4D"


## Display the DataFrame after dropping the row
##print("\nDataFrame after dropping the row with index 1:")df_cleaned)
df16_cleaned

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,NaN,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
4,2024-10-23 00:00:00,54,8,1,B,2934,3512.17742,As per result,NaN,NaN,2934,75,0,0,3512.17742,2934,2934,0,0,4D
5,2024-10-25 00:00:00,60,5,2,B,4600,3504,As per result,NaN,NaN,4600,73,0,0,3504,4600,4600,0,0,4D
6,2024-10-27 00:00:00,70,5,2,B,4400,3036,As per result,NaN,NaN,4400,71,0,0,3036,4400,0,0,4400,4D
7,2024-10-30 00:00:00,76,5,2,T,2237,3248,As per result,NaN,NaN,2237,68,3248,2237,0,0,0,2237,0,4D
8,2024-11-01 00:00:00,82,8,1,B,5067,3460,As per result,NaN,NaN,5067,66,0,0,3460,5067,0,5067,0,4D
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,4D

In [ ]:
# List of all DataFrames to concatenate
#dfs = [df1_cleaned, df2_cleaned, df3_cleaned, df4_cleaned, df5_cleaned, df6_cleaned, df7_cleaned, df8_cleaned, df9_cleaned, df10_cleaned, df11_cleaned, df12_cleaned, df13_cleaned, df14_cleaned, df15_cleaned, df16_cleaned]

# Concatenate all DataFrames vertically (along rows)
#df_concat = pd.concat(dfs, ignore_index=True)

# Display the concatenated DataFrame
#df_concat
################################################################################################################

# Assuming you have 16 DataFrames named df1, df2, ..., df16
dataframes = [df1_cleaned, df2_cleaned, df3_cleaned, df4_cleaned, df5_cleaned, df6_cleaned, df7_cleaned, df8_cleaned, df9_cleaned, df10_cleaned, df11_cleaned, df12_cleaned, df13_cleaned, df14_cleaned, df15_cleaned, df16_cleaned]

# Start with the first DataFrame
concatenated_df = dataframes[0]

# Concatenate one by one
for df in dataframes[1:]:
    concatenated_df = pd.concat([concatenated_df, df], ignore_index=True)
    # Drop column 7 (assuming zero-based index)
concatenated_df.drop(concatenated_df.columns[7], axis=1, inplace=True)
# Print or use the final concatenated DataFrame
concatenated_df

,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
0,2024-10-14 00:00:00,27,2,1,B,3385,3304,NaN,NaN,3385,84,0,0,3304,3385,0,3385,0,1A
1,2024-10-15 00:00:00,29,2,1,B,3092,3244,NaN,NaN,3092,83,0,0,3244,3092,0,3092,0,1A
2,2024-10-25 00:00:00,58,SILO,2,B,4668,2971,NaN,NaN,4668,73,0,0,2971,4668,0,0,4668,1A
3,2024-10-26 00:00:00,65,SILO,2,T,3555,3585,NaN,NaN,3555,72,3585,3555,0,0,3555,0,0,1A
4,2024-10-26 00:00:00,68,SILO,2,T,3246,3753,NaN,NaN,3246,72,3753,3246,0,0,3246,0,0,1A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,2024-10-25 00:00:00,60,5,2,B,4600,3504,NaN,NaN,4600,73,0,0,3504,4600,4600,0,0,4D
93,2024-10-27 00:00:00,70,5,2,B,4400,3036,NaN,NaN,4400,71,0,0,3036,4400,0,0,4400,4D
94,2024-10-30 00:00:00,76,5,2,T,2237,3248,NaN,NaN,2237,68,3248,2237,0,0,0,2237,0,4D
95,2024-11-01 00:00:00,82,8,1,B,5067,3460,NaN,NaN,5067,66,0,0,3460,5067,0,5067,0,4D
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,4D

In [ ]:
concatenated_df.insert(0, 'Sl.No', range(1, len(concatenated_df) + 1))
concatenated_df

,Sl.No,STACKING DATE,RAKE NO,SPUR,SUB PILE,TOP/BOTTOM,ST QNTY,GCV,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,AGING,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100,Pile_id
0,1,2024-10-14 00:00:00,27,2,1,B,3385,3304,NaN,NaN,3385,84,0,0,3304,3385,0,3385,0,1A
1,2,2024-10-15 00:00:00,29,2,1,B,3092,3244,NaN,NaN,3092,83,0,0,3244,3092,0,3092,0,1A
2,3,2024-10-25 00:00:00,58,SILO,2,B,4668,2971,NaN,NaN,4668,73,0,0,2971,4668,0,0,4668,1A
3,4,2024-10-26 00:00:00,65,SILO,2,T,3555,3585,NaN,NaN,3555,72,3585,3555,0,0,3555,0,0,1A
4,5,2024-10-26 00:00:00,68,SILO,2,T,3246,3753,NaN,NaN,3246,72,3753,3246,0,0,3246,0,0,1A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,93,2024-10-25 00:00:00,60,5,2,B,4600,3504,NaN,NaN,4600,73,0,0,3504,4600,4600,0,0,4D
93,94,2024-10-27 00:00:00,70,5,2,B,4400,3036,NaN,NaN,4400,71,0,0,3036,4400,0,0,4400,4D
94,95,2024-10-30 00:00:00,76,5,2,T,2237,3248,NaN,NaN,2237,68,3248,2237,0,0,0,2237,0,4D
95,96,2024-11-01 00:00:00,82,8,1,B,5067,3460,NaN,NaN,5067,66,0,0,3460,5067,0,5067,0,4D
96,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,4D

In [ ]:
new_df=concatenated_df[["Sl.No","Pile_id","STACKING DATE","RAKE NO","SPUR","SUB PILE","TOP/BOTTOM","ST QNTY","GCV","RECLIAM DATE","RC-QNTY","AVAILABLE QUANTITY","AGING","TOP GCV","TOP QNTY","BTM GCV","BTM QNTY","coal above 3500","3100-3500", "<3100"]]
new_df
# Delete the last row
new_df = new_df.iloc[:-1]
new_df
new_df.rename(columns={'Pile_id': 'pile_id','SPUR':'spur','GCV': 'gcv','AGING':'aging'}, inplace=True)
# Convert to proper datetime format
new_df['STACKING DATE'] = pd.to_datetime(df['STACKING DATE'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
new_df

,Sl.No,pile_id,STACKING DATE,RAKE NO,spur,SUB PILE,TOP/BOTTOM,ST QNTY,gcv,RECLIAM DATE,RC-QNTY,AVAILABLE QUANTITY,aging,TOP GCV,TOP QNTY,BTM GCV,BTM QNTY,coal above 3500,3100-3500,<3100
0,1,1A,NaT,27,2,1,B,3385,3304,NaN,NaN,3385,84,0,0,3304,3385,0,3385,0
1,2,1A,NaT,29,2,1,B,3092,3244,NaN,NaN,3092,83,0,0,3244,3092,0,3092,0
2,3,1A,NaT,58,SILO,2,B,4668,2971,NaN,NaN,4668,73,0,0,2971,4668,0,0,4668
3,4,1A,NaT,65,SILO,2,T,3555,3585,NaN,NaN,3555,72,3585,3555,0,0,3555,0,0
4,5,1A,2024-10-23,68,SILO,2,T,3246,3753,NaN,NaN,3246,72,3753,3246,0,0,3246,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,4D,NaT,54,8,1,B,2934,3512.17742,NaN,NaN,2934,75,0,0,3512.17742,2934,2934,0,0
92,93,4D,NaT,60,5,2,B,4600,3504,NaN,NaN,4600,73,0,0,3504,4600,4600,0,0
93,94,4D,NaT,70,5,2,B,4400,3036,NaN,NaN,4400,71,0,0,3036,4400,0,0,4400
94,95,4D,NaT,76,5,2,T,2237,3248,NaN,NaN,2237,68,3248,2237,0,0,0,2237,0
95,96,4D,NaT,82,8,1,B,5067,3460,NaN,NaN,5067,66,0,0,3460,5067,0,5067,0

In [ ]:
pip install sqlalchemy psycopg2 pandas

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.37)
Requirement already satisfied: psycopg2 in /usr/local/lib/python3.11/dist-packages (2.9.10)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Example DataFrame
# Database connection URL
db_url = "postgresql+psycopg2://brioadmin:Gbsm%401234@briopgdb.postgres.database.azure.com:5432/gmr"
# Create SQLAlchemy engine
engine = create_engine(db_url)

# Push DataFrame to PostgreSQL table(Shuvadeep_line)
#new_df.to_sql('pile Details', engine,schema='cyms', if_exists='append', index=False)
#Push DataFrame to PostgreSQL table(Satya_line)
new_df.to_sql('"pile Details"', engine, schema='cyms', if_exists='append', index=False)


print("Data inserted successfully!")

Data inserted successfully!

In [ ]:
from sqlalchemy.orm import sessionmaker

engine = create_engine("postgresql+psycopg2://brioadmin:Gbsm%401234@briopgdb.postgres.database.azure.com:5432/brio_mdm")
Session = sessionmaker(bind=engine)
session = Session()

# session.execute(text(f'TRUNCATE TABLE {mdm_schema}.org_org_business_type'))
session.commit()

session.close()